export const ApiPaths = {
  authLogin: '/workers/auth/login/',
  authRefresh: '/workers/auth/refresh/',
  authLogout: '/workers/auth/logout/',
  workersMe: '/workers/me/',

  homeOverview: '/home/overview/',
  homeFinancialPlan: '/home/financial-plan/',
  homeTrialLessonsWeek: '/home/trial-lessons-week/',
  homeAttendanceStats: '/home/attendance-stats/',
  homeQuickLists: '/home/quick-lists/',
  homeSendReminders: '/home/send-reminders/',

  analyticsOverview: '/analytics/overview/',
  analyticsSalesFunnel: '/analytics/sales-funnel/',
  analyticsFinance: '/analytics/finance/',
  analyticsFinanceDownload: '/analytics/finance/download/',
  analyticsAttendance: '/analytics/attendance/',
  analyticsRoomSchedule: '/analytics/room-schedule/',
  analyticsBookCategories: '/analytics/book-categories/',
  analyticsBooks: '/analytics/books/',
  analyticsBooksAddCopies: '/analytics/books/add-copies/',
  analyticsBook: (id: string | number) => `/analytics/books/${id}/`,
  analyticsBookIssue: (id: string | number) => `/analytics/books/${id}/issue/`,
  analyticsRooms: '/analytics/rooms/',
  analyticsRoom: (id: string | number) => `/analytics/rooms/${id}/`,

  lead: '/lead/',
  leadChoices: '/lead/choices/',
  leadChoicesSources: '/lead/choices/sources/',
  leadSummary: '/lead/summary/',
  leadGroups: '/lead/groups/',
  leadId: (id: string | number) => `/lead/${id}/`,
  leadMove: (id: string | number) => `/lead/${id}/move/`,
  leadCall: (id: string | number) => `/lead/${id}/call/`,
  leadAttendedPayment: (id: string | number) => `/lead/${id}/attended-payment/`,

  students: '/students/',
  studentsStats: '/students/stats/',
  studentsSearch: '/students/search/',
  studentsRestricted: '/students/restricted/',
  studentsBlacklist: '/students/blacklist/',
  student: (id: string | number) => `/students/${id}/`,
  studentBlacklist: (id: string | number) => `/students/${id}/blacklist/`,
  studentFreeze: (id: string | number) => `/students/${id}/freeze/`,
  studentAcademic: (id: string | number) => `/students/${id}/academic/`,
  studentCalendar: (id: string | number) => `/students/${id}/calendar/`,
  studentActivity: (id: string | number) => `/students/${id}/activity/`,
  studentActivityFull: (id: string | number) => `/students/${id}/activity/full/`,
  studentTransactions: (id: string | number) => `/students/${id}/transactions/`,

  group: '/group/',
  groupId: (id: string | number) => `/group/${id}/`,
  groupChoice: (choiceType: string) => `/group/choices/${choiceType}/`,
  groupRooms: '/group/rooms/',
  groupRoom: (id: string | number) => `/group/rooms/${id}/`,
  groupStudents: (id: string | number) => `/group/${id}/students/`,
  groupStoppedStudents: (id: string | number) => `/group/${id}/students/stopped/`,
  groupStudent: (groupId: string | number, studentId: string | number) =>
    `/group/${groupId}/students/${studentId}/`,
  groupAvailableStudents: (id: string | number) => `/group/${id}/available-students/`,
  groupStats: (id: string | number) => `/group/${id}/stats/`,
  groupCalendar: (id: string | number) => `/group/${id}/calendar/`,
  groupLesson: (id: string | number, date: string) => `/group/${id}/lessons/${date}/`,
  groupLessonStatuses: (id: string | number) => `/group/${id}/lesson-statuses/`,
  groupExams: (id: string | number) => `/group/${id}/exams/`,
  groupTransactions: (id: string | number) => `/group/${id}/transactions/`,

  teacher: '/teacher/',
  teacherChoices: '/teacher/choices/',
  teacherSummary: '/teacher/summary/',
  teacherId: (id: string | number) => `/teacher/${id}/`,
  teacherStats: (id: string | number) => `/teacher/${id}/stats/`,
  teacherStudents: (id: string | number) => `/teacher/${id}/students/`,
  teacherLessonsToday: (id: string | number) => `/teacher/${id}/lessons/today/`,
  teacherGroupJournal: (groupId: string | number) => `/group/${groupId}/lessons/`,

  exam: '/exam/',
  examRetake: '/exam/retake/',
  examId: (id: string | number) => `/exam/${id}/`,
  examResults: (id: string | number) => `/exam/${id}/results/`,
  examStudentResult: (id: string | number, studentId: string | number) =>
    `/exam/${id}/results/${studentId}/`,

  task: '/task/',
  taskById: (id: string | number) => `/task/${id}/`,
  taskStatusById: (id: string | number) => `/task/${id}/status/`,
  taskNotifications: '/task/notifications/',
  taskNotificationsMarkAllRead: '/task/notifications/mark-all-read/',
  taskNotification: (id: string | number) => `/task/notifications/${id}/`,

  workers: '/workers/',
  workerChoices: '/workers/choices/',
  worker: (id: string | number) => `/workers/${id}/`,
  workerBranches: '/workers/branches/',
  workerBranch: (id: string | number) => `/workers/branches/${id}/`,

  salarySummary: '/salary/summary/',
  salaryEmployees: '/salary/employees/',
  salaryEmployee: (id: string | number) => `/salary/employees/${id}/`,
  salaryEmployeeStatus: (id: string | number) => `/salary/employees/${id}/status/`,
  salaryIncomeDynamics: '/salary/income-dynamics/',
  salaryHistory: '/salary/history/',
  salaryTariffs: '/salary/tariffs/',
  salaryTariff: (id: string | number) => `/salary/tariffs/${id}/`,

  transactions: '/transactions/',
  transactionsPayment: '/transactions/payment/',
  transactionsRefund: '/transactions/refund/',
  transactionsStats: '/transactions/stats/',

  penaltyTypes: '/penalty/types/',
  penaltyType: (id: string | number) => `/penalty/types/${id}/`,
  penaltyCalendar: '/penalty/calendar/',
  penalty: '/penalty/',
  penaltyId: (id: string | number) => `/penalty/${id}/`,

  settingsBranches: '/settings/branches/',
  settingsBranch: (id: string | number) => `/settings/branches/${id}/`,
  settingsRoles: '/settings/roles/',
  settingsRolesUsersSearch: '/settings/roles/users-search/',
  settingsRole: (id: string | number) => `/settings/roles/${id}/`,
  settingsRolesMyPermissions: '/settings/roles/me/permissions/',
  settingsRoleAction: (id: string | number, action: string) => `/settings/roles/${id}/${action}/`,
  settingsRoleGrant: (id: string | number) => `/settings/roles/${id}/grant/`,
  settingsRoleUsers: (id: string | number) => `/settings/roles/${id}/users/`,
  settingsExpenses: '/settings/expenses/',
  settingsExpenseCategories: '/settings/expenses/categories/',
  settingsExpensesSummary: '/settings/expenses/summary/',
  settingsExpensesLimit: '/settings/expenses/limit/',
  settingsExpense: (id: string | number) => `/settings/expenses/${id}/`,
  settingsMarketingOverview: '/settings/marketing/overview/',
  settingsMarketingSources: '/settings/marketing/sources/',
  settingsMarketingSource: (id: string | number) => `/settings/marketing/sources/${id}/`,
  settingsMarketingFunnel: '/settings/marketing/funnel/',
  settingsMarketingFunnelStage: '/settings/marketing/funnel/stage/',
  settingsMarketingFunnelStageId: (id: string | number) => `/settings/marketing/funnel/stage/${id}/`,
  settingsMarketingConversionFunnel: '/settings/marketing/conversion-funnel/',
  settingsMarketingOutcomes: '/settings/marketing/outcomes/',
  settingsMarketingPaymentHistory: '/settings/marketing/payment-history/',
} as const;
